### ISSUE TITLE
Text centering issue when using with ebitenui

### ISSUE THREAD

**Issue by quasilyte** [hajimehoshi/bitmapfont#10]
Related issue: https://github.com/ebitenui/ebitenui/issues/69

I'm creating an issue here to create a reference that can be useful when we're done with this issue, so other people can find the problem roots easier.

**Comment by hajimehoshi** [comment]
I don't think centering a text is this library's responsibility.

**Comment by quasilyte** [comment]
It's not, but `text.Draw` with x offset of 11 draws a text with this font using an offset of ~6.
It happens only with this font so far and how to address this is unclear.

**Comment by hajimehoshi** [comment]
I've never seen such an issue with this font so ebitenui seems the right place to discuss.
