### ISSUE TITLE
Refactor to create bdf parsing package

### ISSUE THREAD

**Issue by CamilleScholtz** [hajimehoshi/bitmapfont#4]
Would it be possible to refactor the code so that an user of this package can parse a `.bdf` file and that it will return a `font.Face`?

**Comment by hajimehoshi** [comment]
Theoretically yes, but I don't have enough bandwidth to implement a general BDF parser.

**Comment by mortenson** [comment]
I've found https://github.com/zachomedia/go-bdf to work well for creating font.Faces from bdf files.
